### ISSUE TITLE
No matching function for call to ‘curl::curl_easy::curl_easy(curl::curl_ios<std::__cxx11::basic_ostringstream<char> >&)'

### ISSUE THREAD

**Issue by foreverska** [JosephP91/curlcpp#61] opened 2015-12-01 16:44 UTC
It would seem most recent commit removed ability to initialize curl_easy using a curl_ios<ostringstream> without updating the README of this change.  Should be replaced with a reference to recv_header.cpp which seems to be an example of the new way to write responses to a variable.

**Comment by JosephP91** [comment] 2015-12-01 16:58
Hi @foreverska !
You can still initialize a curl_easy object with a curl_ios instance. What kind of problem you encountered?

**Comment by foreverska** [comment] 2015-12-01 17:04
The error which titles this issue happens when I try to compile the example to put the response in a variable given in the README and my own code which at the time was modeled directly after it.  g++ goes on to list the possible function candidates none of which are close to initialization with a curl_ios instance.

**Comment by JosephP91** [comment] 2015-12-01 17:06
Ok, can you post the piece of code in which you are initializing curl_easy and declaring curl_ios?

**Comment by foreverska** [comment] 2015-12-01 17:13
For testing I copied and pasted the code provided in the README (the 4th Simple Usage Example) into a local file called test.cpp file and compiled it and here is the output:

```
adam@adam-PC:~/Documents/Programming/config/neo4j$ g++ -std=c++11 src/test.cpp -I inc/ -I ../../vendor/curlcpp/include/ -L ../../vendor/curlcpp/build/src/ -lcurlcpp -lcurl
src/test.cpp: In function ‘int main()’:
src/test.cpp:13:26: error: no matching function for call to ‘curl::curl_easy::curl_easy(curl::curl_ios<std::__cxx11::basic_ostringstream<char> >&)’
     curl_easy easy(writer);
                          ^
In file included from src/test.cpp:1:0:
../../vendor/curlcpp/include/curl_easy.h:893:9: note: candidate: curl::curl_easy::curl_easy(const curl::curl_easy&)
         curl_easy(const curl_easy &);
         ^
../../vendor/curlcpp/include/curl_easy.h:893:9: note:   no known conversion for argument 1 from ‘curl::curl_ios<std::__cxx11::basic_ostringstream<char> >’ to ‘const curl::curl_easy&’
../../vendor/curlcpp/include/curl_easy.h:888:18: note: candidate: curl::curl_easy::curl_easy(long int)
         explicit curl_easy(const long);
                  ^
../../vendor/curlcpp/include/curl_easy.h:888:18: note:   no known conversion for argument 1 from ‘curl::curl_ios<std::__cxx11::basic_ostringstream<char> >’ to ‘long int’
../../vendor/curlcpp/include/curl_easy.h:883:9: note: candidate: curl::curl_easy::curl_easy()
         curl_easy();
         ^
../../vendor/curlcpp/include/curl_easy.h:883:9: note:   candidate expects 0 arguments, 1 provided
```

**Comment by JosephP91** [comment] 2015-12-01 17:37
@foreverska Holy cow! Two methods implementation were missing. I pushed a fix right now. Can you update your curlcpp local version and let me know if the problem is fixed?

**Comment by foreverska** [comment] 2015-12-01 17:47
I did a pull and now test.cpp compiles and runs correctly.

I already migrated my code to the recv_header.cpp style code so all I can say about that is the push didn't break anything for me.  But this will be very helpful for new people.

**Comment by JosephP91** [comment] 2015-12-01 17:49
Very well! Thank you!

**Closed by JosephP91** 2015-12-01 17:49 UTC
