### ISSUE TITLE
memory corruption possibly caused by curl_easy 

### ISSUE THREAD

**Issue by ncalad** [JosephP91/curlcpp#71] opened 2016-02-18 23:16 UTC
We are having a memory corruption problem that seems to be caused by the creation of the curl_easy object on the stack. If we return string() immediately after creating the object, we see memory corruption. If we return before creating the object, the corruption doesn't occur. We also note problems and crashes with gethostname (see stack trace below). These tests are being run on Ubnutu 14.02 Linux and with gcc 4.8.4. 

 const std::string TestClass::SendRequest(const string &request) {
            LOG(LogLevel::Debug, request);

            // Create a ostringstream object to receive the response body
            ostringstream body_var;
            ostringstream header_var;

            // The "body" stream will put the body content into "body_var"
            curl_ios<ostringstream> body(body_var);

            // The "header" stream will put the headers into "header_var"
            curl_ios<ostringstream> header(header_var);

            // Easy object to handle the connection.
            curl_easy easy;

            return string();
}

#0  __tsearch (key=key@entry=0x7fffeb5eaf58, vrootp=vrootp@entry=0x2500435455002e28, 
   compar=compar@entry=0x7ffff4e4c610 <known_compare>) at tsearch.c:250
#1  0x00007ffff4e4d21f in __GI___nss_lookup_function (ni=ni@entry=0x2500435455002e00, 
   fct_name=fct_name@entry=0x7ffff4eae5e3 "gethostbyname4_r") at nsswitch.c:468
#2  0x00007ffff4dfc6a2 in gaih_inet (name=<optimized out>, service=<optimized out>, req=<optimized out>, pai=<optimized out>, 
   naddrs=<optimized out>) at ../sysdeps/posix/getaddrinfo.c:841
#3  0x00000000000003c2 in ?? ()
#4  0x0000000000000002 in ?? ()
#5  0x0000000000000000 in ?? ()
(gdb)

**Comment by ncalad** [comment] 2016-02-18 23:16
One other thing. I removed curlcpp from the app, and instead wrapped curl in a c++ object of our own and we haven't had corruption since.

**Comment by JosephP91** [comment] 2016-02-19 12:41
hi @ncalad !
I would like to reproduce the problem, but I can't. I have wrote an example function:

`````
#include <iostream>
#include <ostream>

#include "curl_easy.h"
#include "curl_form.h"
#include "curl_ios.h"
#include "curl_exception.h"

using std::ostringstream;
using curl::curl_easy;
using curl::curl_ios;

std::string foo() {
    ostringstream str;
    curl_ios<ostringstream> writer(str);
    curl_easy easy;
    return std::string();
}

int main() {
    foo();
    return 0;
}
`````

But I did not have any crash.

**Comment by ncalad** [comment] 2016-02-19 14:20
HI Giuseppe,

I will try to create a test program that shows the problem.

Thanks
Andy

Giuseppe wrote:

**Comment by JosephP91** [comment] 2016-02-19 14:24
Good! I will wait for your test program. Thank you!

**Comment by JosephP91** [comment] 2016-03-27 15:36
@ncalad any news about the test program?

**Comment by ncalad** [comment] 2016-03-30 14:02
We think it was a build problem and not an issue with curlcpp since it 
has gone away.

-- Andy



Giuseppe wrote:

**Comment by JosephP91** [comment] 2016-03-30 14:04
Ok. Thank you for letting me know that :) I will close the issue since it's not related to curlcpp.

**Closed by JosephP91** 2016-03-30 14:04 UTC
